---
- name: Install OpenSSL
  apt: name=openssl state=present

- name: Ensure certificates directory exists
  file: path={{ certificates_directory }} state=directory

- name: Generate Certification Authority for this host
  command: openssl req -newkey {{ ca_key_type }} -nodes -x509 -subj "/C=/ST=/L=/O=/CN=CA of {{ fully_qualified_domain_name  }}" -days {{ ca_validity_days }}  -keyout {{ ca_key }} -out {{ ca_certificate }} -outform PEM creates={{ ca_certificate }}

